name: tests

on: [push, pull_request]

jobs:
  test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

      - uses: actions/checkout@v1

      - name: Install rbenv on macos-latest
        if: matrix.os == 'macos-latest'
        run: |
          brew install rbenv -v

      - name: Install rbenv on ubuntu-latest
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install rbenv

      - name: Install ruby 2.6.0
        run: |
          rbenv install 2.6.0

      - name: Install bundler
        run: |
          gem install bundler:2.0.2

      - name: Install gems
        run: |
          bundle install

      - name: Run test
        run: |
          bundle exec rake spec