name: tests

on: [push, pull_request]

jobs:
  test-linux:
    name: Run test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Get rbenv and ruby-build
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      - name: Install dependencies required to install Ruby
        run: |
          sudo apt-get install -y libreadline-dev

      - name: Install ruby 2.6.0
        run: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          rbenv install 2.6.0

      - name: Run tests
        run: |
          export PATH="$HOME/.rbenv/versions/2.6.0/bin:$PATH"
          bundle install
          bundle exec rake spec

  test-mac-os:
    name: Run test on macos-latest
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v1

      - name: Install rbenv
        run: |
          brew update
          brew install rbenv


      - name: Install ruby 2.6.0
        run: |
          echo $PATH
          export PATH="$HOME/.rbenv/bin:$PATH"
          rbenv install 2.6.0

      - name: Install bundler
        run: |
          echo $PATH
          export PATH="$HOME/.rbenv/bin:$PATH"
          gem install bundler:2.0.2

      - name: Install gems
        run: |
          bundle install

      - name: Run test
        run: |
          bundle exec rake spec