name: tests

on: [push, pull_request]

jobs:
  test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

      - uses: actions/checkout@v1

      - name: Clone rbenv to ~/.rbenv
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv


      - name: Setup rbenv
        run: |
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          npm config delete prefix
          source ~/.bashrc

      - run: |
          ls -a ~/
          echo "========"
          ls ~/.rbenv/bin
          echo $PATH

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      - name: Install ruby 2.6.0
        run: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          rbenv install 2.6.0

      - name: Install bundler
        run: |
          gem install bundler:2.0.2

      - name: Install gems
        run: |
          bundle install

      - name: Run test
        run: |
          bundle exec rake spec