name: tests

on: [push, pull_request]

jobs:
  test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

      - uses: actions/checkout@v1

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install bundler
        run: |
          gem install bundler:2.0.2

      - name: Install gems
        run: |
          bundle install

      - name: Run test
        run: |
          bundle exec rake spec