name: tests

on: [push, pull_request]

jobs:
  test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:

      - uses: actions/checkout@v1

      - name: Get rbenv and ruby-build
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      - name: Install dependencies required to install Ruby
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libreadline-dev

      - name: Install ruby 2.6.0
        run: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          rbenv install 2.6.0

      - name: Run tests
        run: |
          export PATH="$HOME/.rbenv/versions/2.6.0/bin:$PATH"
          gem install bundler:2.0.2
          bundle install
          bundle exec rake spec