name: tests

on: [push, pull_request]

jobs:
  test:
    name: Run test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v1

      - name: Get rbenv and ruby-build
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      - name: Install dependencies required to install Ruby
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libreadline-dev

      - name: Install ruby 2.6.0
        run: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          rbenv install 2.6.0

      - name: Run tests
        run: |
          export PATH="$HOME/.rbenv/versions/2.6.0/bin:$PATH"
          gem install bundler:2.0.2
          bundle install
          bundle exec rake spec

  test-windows:
    name: Run test on windows
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v1

      - name: Install ruby 2.6.0.1 and bundler
        run: |
          choco install ruby --version 2.6.0.1
          gem install bundler:2.0.2

      - name: Install gems
        run: |
          bundle install
      - name: Run test
        run: |
          bundle exec rake spec

  # ft-linux-macos:
  #   name: Run FTs on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   needs: test
  #   env:
  #     RUBY_PLUGIN_BRANCH: grpc
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]

  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: echo $RUBY_PLUGIN_BRANCH

  #     - name: Get rbenv and ruby-build
  #       run: |
  #         git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  #         git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

  #     - name: Install dependencies required to install Ruby
  #       if: matrix.os == 'ubuntu-latest'
  #       run: |
  #         sudo apt-get install -y libreadline-dev

  #     - name: Install ruby 2.6.0
  #       run: |
  #         export PATH="$HOME/.rbenv/bin:$PATH"
  #         rbenv install 2.6.0

  #     - name: Setup go 1.13.1
  #       uses: actions/setup-go@v1
  #       with:
  #         go-version: 1.13.1

  #     - name: Install gauge
  #       run: |
  #         git clone --depth=1 https://github.com/getgauge/gauge.git
  #         cd gauge
  #         go run build/make.go --verbose
  #         go run build/make.go --install --prefix=/tmp/

  #     - name: Run tests
  #       run: |
  #         export PATH="$HOME/.rbenv/versions/2.6.0/bin:/tmp/bin:$PATH"
  #         gem install bundler:2.0.2
  #         bundle install
  #         bundle exec rake install force_install
  #         git clone --depth=1 https://github.com/getgauge/gauge-tests
  #         cd gauge-tests
  #         gauge install
  #         gauge -v
  #         ./gradlew clean rubyFT

  # ft-windows:
  #   name: Run FTs on windows
  #   runs-on: windows-latest
  #   needs: test-windows
  #   env:
  #     RUBY_PLUGIN_BRANCH: grpc

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Setup go 1.13.1
  #       uses: actions/setup-go@v1
  #       with:
  #         go-version: 1.13.1

  #     - name: Install ruby 2.6.0.1 and bundler
  #       run: |
  #         choco install ruby --version 2.6.0.1
  #         gem install bundler:2.0.2

  #     - name: Install gauge
  #       run: |
  #         git clone --depth=1 https://github.com/getgauge/gauge.git
  #         cd gauge
  #         go run build/make.go --verbose
  #         go run build/make.go --install

  #     - name: Install gauge-ruby
  #       shell: pwsh
  #       run: |
  #         ${env:PATH} += ";C:\Program Files\gauge\bin"
  #         bundle install
  #         bundle exec rake install force_install

  #     - name: Run tests
  #       shell: pwsh
  #       run: |
  #         ${env:PATH} += ";C:\Program Files\gauge\bin"
  #         git clone --depth=1 https://github.com/getgauge/gauge-tests
  #         cd gauge-tests
  #         gauge install
  #         gauge -v
  #         .\gradlew.bat clean rubyFT

  lsp-linux:
    name: Run lsp on ubuntu-latest
    runs-on: ubuntu-latest
    # needs: test
    env:
      RUBY_PLUGIN_BRANCH: grpc
      USE_LOCAL_GAUGE_RUBY: true

    steps:
      - uses: actions/checkout@v1
      - run: |
          echo $GITHUB_WORKSPACE
          echo "::set-env name=LOCAL_GAUGE_RUBY_PATH::$GITHUB_WORKSPACE"
      - run: |
            echo $LOCAL_GAUGE_RUBY_PATH
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Get rbenv and ruby-build
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      - name: Install dependencies required to install Ruby
        run: |
          sudo apt-get install -y libreadline-dev

      - name: Install ruby 2.6.0
        run: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          rbenv install 2.6.0

      - name: Setup go 1.13.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1

      - name: Install gauge
        run: |
          git clone --depth=1 https://github.com/getgauge/gauge.git
          cd gauge
          go run build/make.go --verbose
          go run build/make.go --install --prefix=/tmp/
          echo "::add-path::/tmp/bin"
      - name: Prep gauge-js
        run: |
          git clone https://github.com/getgauge/gauge-js.git
          cd gauge-js
          npm install
        shell: bash

      - name: Install gauge-js
        run: |
          cd gauge-js
          npm run installPlugin

      - name: Run tests
        run: |
          node -v
          export PATH="$HOME/.rbenv/versions/2.6.0/bin:/tmp/bin:$PATH"
          gem install bundler:2.0.2
          bundle install
          bundle exec rake install force_install
          git clone --depth=1 --branch=local-gauge-ruby https://github.com/getgauge/gauge-lsp-tests
          cd gauge-lsp-tests
          npm install
          gauge install
          gauge -v
          gauge run --tags='!knownIssue & (actions_on_project_load | actions_on_file_edit)' --env=ruby-wd --verbose

      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logs-linux
          path: gauge-lsp-tests/logs

  lsp-windows:
    name: Run lsp on windows-latest
    runs-on: windows-latest
    # needs: test-windows
    env:
      RUBY_PLUGIN_BRANCH: grpc
      USE_LOCAL_GAUGE_RUBY: true

    steps:
      - uses: actions/checkout@v1

      - run: |
          echo $GITHUB_WORKSPACE
          echo "::set-env name=LOCAL_GAUGE_RUBY_PATH::$GITHUB_WORKSPACE"

      - run: |
          echo $LOCAL_GAUGE_RUBY_PATH

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install ruby 2.6.0.1 and bundler
        run: |
          choco install ruby --version 2.6.0.1
          gem install bundler:2.0.2

      - name: Setup go 1.13.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1

      - name: Install gauge
        run: |
          git clone --depth=1 https://github.com/getgauge/gauge.git
          cd gauge
          go run build/make.go --verbose
          go run build/make.go --install
          echo "::add-path::C:\\Program Files\\gauge\\bin"

      - name: Prep gauge-js
        run: |
          git clone https://github.com/getgauge/gauge-js.git
          cd gauge-js
          npm install

      - name: Install gauge-js
        run: |
          cd gauge-js
          npm run installPlugin

      - name: Install gauge ruby
        run: |
          gem install bundler:2.0.2
          bundle install
          bundle exec rake install force_install

      - name: Clone LSP tests
        run: |
          git clone --depth=1 --branch=local-gauge-ruby https://github.com/getgauge/gauge-lsp-tests
          cd gauge-lsp-tests
          npm install
          gauge install
          gauge -v

      - name: Run tests
        run: |
          cd gauge-lsp-tests
          gauge run --tags='!knownIssue & (actions_on_project_load | actions_on_file_edit)' --env=ruby-wd --verbose

      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logs-windows
          path: gauge-lsp-tests/logs